#Time Stream DB variables
INFRA_TSB_VARIABLES = {
  MAGNETIC_STORE_RETENTION_PERIOD_IN_DAYS = 70
  MEMORY_STORE_RETENTION_PERIOD_IN_HOURS  = 9
}

#MSK Cluster variable
INFRA_MSK_CLUSTER_VARIABLE = {
  AUTO_CREATE_TOPICS_ENABLE    = false
  DELETE_TOPIC_ENABLE          = true
  REPLICATION_FACTOR           = 3
  MINIMUM_INSYNC_REPLICAS      = 2
  PARTITION_NUMBER             = 8
  LOG_RETENTION_HOURS          = 2
  MSK_LOG_RETENTION_IN_DAYS    = 3
  MSK_NUMBER_OF_BROKER_NODES   = 3
  MSK_ENHANCED_MONITORING      = "DEFAULT"
  MSK_BROKER_INSTANCE_TYPE     = "kafka.t3.small"
  MSK_EBS_STORAGE_VOLUME       = 1000
  MSK_CLIENT_BROKER_ENCRYPTION = "TLS_PLAINTEXT"
}

#Kafka topic variable
INFRA_KAFKA_TOPIC_VARIABLE = {
  TOPIC_REPLICATION_FACTOR    = 2
  TOPIC_PARTITIONS            = 100
  TOPIC_CONFIG_SEGMENT_MS     = 20000
  TOPIC_CONFIG_CLEANUP_POLICY = "compact"
}


