variable "CORE_SIZING_LAMBDA_PROPERTIES" {
  type = object({
    CORE_SIZING_LAMBDA_FUN_NAME          = string
    CORE_SIZING_LAMBDA_ALIAS_NAME        = string
    CORE_SIZING_LAMBDA_CODE_JAR_NAME     = string
    CORE_SIZING_LAMBDA_OTEL_SERVICE_NAME = string
    CORE_SIZING_LAMBDA_OTEL_LAYER_ARN    = string

    CORE_SIZING_MSK_CONSUMER_LAMBDA_PERSISTER_REGION            = string
    CORE_SIZING_MSK_CONSUMER_LAMBDA_PERSISTER_NAME              = string
    CORE_SIZING_MSK_CONSUMER_LAMBDA_PERSISTER_OTEL_SERVICE_NAME = string
    CORE_SIZING_MSK_CONSUMER_LAMBDA_PERSISTER_ALIAS_NAME        = string

    CORE_SIZING_LAMBDA_SUBNETS = list(string)

    CORE_SIZING_LAMBDA_TIMESTREAM_DB_NAME   = string
    CORE_SIZING_LAMBDA_TIMESTREAM_TBL_NAME  = string
    CORE_SIZING_LAMBDA_MSK_MODEL_TOPIC_NAME = string

    CORE_SIZING_LAMBDA_SECURITY_GP_IDS           = any
    CORE_SIZING_LAMBDA_PERSISTER_SECURITY_GP_IDS = any
  })
}

variable "CORE_SIZING_LAMBDA_BUCKET_INFORMATION" {
  type = object({
    CRS_LAMBDA_S3_BUCKET_CODE_REPO_ID              = string
    CRS_LAMBDA_S3_OBJECT_RESOURCE_KEY              = string
    CRS_LAMBDA_PERSISTER_S3_BUCKET_CODE_REPO_ID    = string
    CRS_LAMBDA_PERSISTER_S3_OBJECT_RESOURCE_KEY    = string
    CRS_LAMBDA_S3_OBJECT_RESOURCE_SOURCE           = string
    CRS_LAMBDA_PERSISTER_S3_OBJECT_RESOURCE_SOURCE = string


  })
}

variable "CORE_SIZING_LAMBDA_IAM_ROLE_ARN" {
  type = object({
    CRS_LAMBDA_IAM_ARN           = string
    CRS_LAMBDA_PERSISTER_IAM_ARN = string
  })
}

variable "CORE_SIZING_LAMBDA_PERSISTER_MSK_CLUSTER" {}
