variable "NIBS_ACCOUNT_ANAPLAN_IO_DNS_NAME" {}

variable "CORE_SIZING_LAMBDA_SUBDOMAIN_NAME" {}

variable "MSK_BROKER_SUBDOMIAN_NAME" {}

variable "ROUTE53_ANAPLAN_IO_ZONE_ID" {}

variable "CORE_SIZING_LOAD_BALANCER" {}

variable "MSK_CLUSTER_LOAD_BALANCER" {}


