variable "CRS_CLOUD_WATCH_LOG_PROPERTIES" {
  type = object({
    CRS_SIZING_PROMTAIL_FILTER_NAME    = string
    CRS_PERSISTER_PROMTAIL_FILTER_NAME = string
    CRS_PROMTAIL_FILTER_DEST_ARN       = any
    CORE_SIZING_LAMBDA_LOG_GROUP_NAME  = string
    KAFKA_CORE_CONSUMER_LOG_GROUP_NAME = string
  })
}
